### ISSUE TITLE
Project Maven Deployment

### ISSUE THREAD

**Issue by ambrusadrianz** [tylerbenson/zipkin-datadog-reporter#2]
Hi,

We would like to use this DataDog Zipkin reporter in our project. Do you have any plans on making the deployment to a maven repository? Or maintaining the project?

If not, and if you don't mind, we would like to release our forked version on Maven Central with some slight modifications/improvements.

**Comment by tylerbenson** [comment]
Thanks for checking with me.  Let me get back to you next week.  Need to confirm a few things first.

**Comment by ambrusadrianz** [comment]
Hey @tylerbenson, after all we decided to create our own fork and release it to Maven Central. You can find the repo [here](https://github.com/smartupio/zipkin-datadog-reporter).

There were some bugfixes that we made, if you'd like I could provide a PR for your repo as well. 

The first one was a case where the span kind is null, `DDMappingSpan` would throw a NPE. 

The second one was an issue with the `InputStream` skipping code, it would throw a `stream is closed` exception, because the resource was already closed by the reader. 

There is a third issue which only happens with the p6spy brave instrumentation. It's possible that the `spanName` does not contain any alphanumerical character and that is rejected by the DataDog tracing API. There we plan to introduce some sort of sanitization.

I wanted to ask you why is the response `InputStream` skipping needed? I could not figure it out.

**Comment by tylerbenson** [comment]
@ambrusadrianz a couple of things...

If you are going to fork it, you should do a proper fork, not just [reimport](https://github.com/smartupio/zipkin-datadog-reporter/commit/fced4376875eb84c7929cb288d69df689d9c2c86) my code into a new repo and not maintain the history.

Technically, while this repo is source visible, I don't have any license included, so you should at least wait until I get a license added to the repo.

Finally, you didn't really wait to hear back from me...

If I add a license, do you agree to do a proper fork?

**Comment by tylerbenson** [comment]
Another option I'd consider is granting you push permissions on this repo.  Would you prefer that?

**Comment by ambrusadrianz** [comment]
Sorry for the late response, I was on holiday. Sorry for not waiting for you and copying your code without permission. I would gladly fork this repo and contribute the work I did on it.

Please add a license on it. After that I will fork it and make a PR with the deployment process and some bugfixes that I made. The deployment script could be easily reused, you would just need to provide and encrypt your own credentials with `travis-cli`.

**Comment by tylerbenson** [comment]
I've added a license file.  Let me know what else you need me to do.

**Comment by matelang** [comment]
Hi @tylerbenson ,

sorry for not doing the fork from the beginning, it was a mistake from our end, we definitely encourage OSS software in our company culture and we thank you for creating this project and investing the time in it.

We have a slightly different tooling, so we changed some things to make it convenient for ourselves.

We now have forked the repo, and moved the non-fork one to another place temporarily.
We are going to delete the non-fork version shortly.

Feel free to import our changes, if you want we can create a PR. 

Also, if you need help in publishing your own project to maven central by modifying our fork feel free to reach out, either myself or @ambrusadrianz are happy to help.

We have also included the apache license from the origin repository.

If the above is acceptible to you please close this issue.


Cheers,
Mate

**Comment by tylerbenson** [comment]
Thanks for correcting the fork and giving me the credit.  I'll go ahead and close this for now.  Good luck and thanks for taking the reigns.
